version: '3'
services:
  debezium_tester_app:
    image: debezium_tester_app
    container_name: debezium_tester_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - debezium-compose-network
    depends_on:
      - connect-debezium
      - zookeeper-debezium
      - kafka-debezium
      - tester_db


  zookeeper-debezium:
    image: debezium/zookeeper:1.4
    container_name: zookeeper-debezium
    hostname: zookeeper-debezium
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
      - debezium-compose-network

  kafka-debezium:
    image: debezium/kafka:1.4
    container_name: kafka-debezium
    hostname: kafka-debezium
    ports:
     - 9092:9092
    links:
     - zookeeper-debezium
    environment:
     - ZOOKEEPER_CONNECT=zookeeper-debezium:2181
    networks:
      - debezium-compose-network

  connect-debezium:
    image: debezium/connect:1.4
    container_name: connect-debezium
    hostname: connect-debezium
    ports:
     - 8083:8083
    links:
     - kafka-debezium
    environment:
     - BOOTSTRAP_SERVERS=kafka-debezium:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - debezium-compose-network

  tester_db:
    image: postgres
    hostname: tester_db
    container_name: tester_db
    shm_size: 4gb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

    networks:
      - debezium-compose-network

  console:
    image: docker.redpanda.com/vectorized/console:latest
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka-debezium:9092"]
        connect:
          enabled: true
          clusters:
            - name: connect-debezium
              url: http://connect-debezium:8083
    ports:
      - 8080:8080
    networks:
      - debezium-compose-network
    depends_on:
      - kafka-debezium

networks: 
  debezium-compose-network:
    driver: bridge