[project]
name = "debezium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.12.0",
    "fastapi[standard]>=0.115.4",
    "ruff>=0.7.1",
]
